name: Push

on:
  schedule:
    - cron: '0 12 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.1
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: 'Run Python'
      run: python3 ./main.py
      
    - name: 'Show Diff'
      run: git add .
    
    - name: 'Push Calendar'
      uses: actions-go/push@7ad7ce209f2a038e7bca929b7a4c92026363f856
      with:
        commit-message: "update"
        remote: master
