name: Push

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: 'Run Python'
      run: python3 ./main.py
      
    - name: commit
      run: |
        git config --global user.email jable@jable.tv
        git config --global user.name GithubActions
        git add .
        git commit -m "update" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
